### ISSUE TITLE
Despues del cambio de tarifas del 1/junio no funciona

### ISSUE THREAD

**Issue by khab666** [azogue/aiopvpc#18]
Buenos dias,

Despues del cambio de tarifas de hoy no funciona correctamente el componente, He actualizado el componente a la ultiam version 2.1.2, pero no sé como configurarlo para que funcione correctamente.
La instalación la hice desde "añadir integración" de HA, no lo tengo como custom component.

Podrías indicarme como solucionarlo por favor? 

Muchas gracias de antemano!

**Comment by revin34** [comment]
Aqui tienes las instrucciones para arreglarlo mientras no salga el fix que se ha incluido en la próxima release de Home Assistant

https://github.com/azogue/aiopvpc/issues/16

**Comment by azogue** [comment]
Hola @khab666,

las dependencias de cada integración que se añade en HA se gestionan por HA en un entorno aislado, no sé exactamente dónde has instalado la última versión 2.1.2, pero imagino que HA sigue usando la que tiene vinculada a su versión (si no es así, te pediría más información sobre el error: logs, capturas, etc.)

La versión de HA 2021.6.0 está **prevista para mañana**, y ya contiene el fix, por lo que, si puedes esperar 1 día, ese es el camino más _suave_.
Si tienes mucha prisa hay 2 maneras:
- El método comentado en https://github.com/azogue/aiopvpc/issues/16#issuecomment-851649290, como _custom component_, que yo mismo aconsejé y estoy usando. No necesita instalar ninguna librería (está auto contenido)
- Hay usuarios avisando de que la última beta de HA 2021.6.0 ya incluye el patch, por lo que, con HA OS, se puede cambiar al sistema de betas y actualizar ya.

**Comment by khab666** [comment]
Perfecto, pues esperaré a mañana, no me va de un dia...
Muchas gracias!
