### ISSUE TITLE
Node red integration

### ISSUE THREAD

**Issue by Ataraxiall** [azogue/aiopvpc#24]
Hi!
Im trying to use the librray to export the best 6 hous of energy price to node red in json.

¿It possible? i can  execute python programs in node red.

Thanks!

**Comment by azogue** [comment]
Hi @Ataraxiall, 

I don't have any experience with Node-Red, sorry. 

I know a lot of people use it as a HomeAssistant add-on, is that your case? 

If so, I suppose you have the `PVPC hourly pricing` integration in HA, which is using this library to get the prices. In that case, if you can access the state and attributes of the PVPC sensor, everything you need it's there: all prices for the current day are present in the sensor attributes, named with a `price_XXh` pattern, so you just need to get those 24 attributes and filter the best 6

**Comment by azogue** [comment]
Closing this one, as it's not related to this library
