### ISSUE TITLE
Component errors in ha log

### ISSUE THREAD

**Issue by javiges** [azogue/aiopvpc#36]
I use the plugin with the token, and I have several errors in the ha log that fills it up.
I give an example:

2021-12-03 15:13:38 ERROR (SyncWorker_50) [aiopvpc.pvpc_data] Forbidden error with 'https://api.esios.ree.es/archives/70/download_json?locale=es&date=2021-11-30' -> Headers:  <CIMultiDictProxy('Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store', 'Connection': 'close', 'Content-Length': '866', 'X-Iinfo': '14-151164377-0 2NNN RT(1638540818356 35) q(0 -1 -1 -1) r(0 -1) B15(11,1720275,0)', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'visid_incap_1885724=VDr4YmSlTrCza1XnDKv1nBImqmEAAAAAQUIPAAAAAACg4JdrwdFB7ffJdP7W1Muh; expires=Fri, 02 Dec 2022 17:16:12 GMT; HttpOnly; path=/; Domain=.esios.ree.es; Secure; SameSite=None', 'Set-Cookie': 'incap_ses_1484_1885724=zUq8Hjfug1nOFp32JzqYFBImqmEAAAAArCR/L+VGJF4cgA5VadLWfw==; path=/; Domain=.esios.ree.es; Secure; SameSite=None')>

**Comment by ibarbech** [comment]
Same error here.

**Comment by jaconejero** [comment]
In my case it stopped working on Nov 29th

**Comment by cyberdie** [comment]
Same problema here. I use the plugin with the token but a lot of errors in HA log.
The price data is updating but a lot of errors like this:

_```
Logger: aiopvpc.pvpc_data
Source: /usr/local/lib/python3.9/site-packages/aiopvpc/pvpc_data.py:135
First occurred: 10:24:51 (4 occurrences)
Last logged: 10:31:00

Forbidden error with 'https://api.esios.ree.es/archives/70/download_json?locale=es&date=2021-12-21' -> Headers: <CIMultiDictProxy('Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store', 'Connection': 'close', 'Content-Length': '861', 'X-Iinfo': '4-62302767-0 0CNN RT(1640078689962 1028) q(0 -1 -1 0) r(0 -1) B15(11,1720275,0)', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'visid_incap_1885724=uyg7w7EFQtyhRrbJ8RwgggqfWKdwWEAAAAAQUIPAAAAAACZ01Zk08CU+QpwNOXT7gZF; expires=Wed, 21 Dec 2022 07:38:52 GMT; HttpOnly; path=/; Domain=.esios.ree.es; Secure; SameSite=None', 'Set-Cookie': 'incap_ses_508_1885724=tcfLECXQ1GP7VA1qyscMB2KdwWEAAAAAgggKHgT/8y+jOs8Z+5V5K7MXQ==; path=/; Domain=.esios.ree.es; Secure; SameSite=None')>
Forbidden error with 'https://api.esios.ree.es/archives/70/download_json?locale=es&date=2021-12-21' -> Headers: <CIMultiDictProxy('Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store', 'Connection': 'close', 'Content-Length': '863', 'X-Iinfo': '5-15052431-0 0CNN RT(1640078700241 15216) q(0 -1 -1 -1) r(0 -1) B15(11,1720275,0)', 'Strict-Transport-Security': 'max-age=31536000')>
Forbidden error with 'https://api.esios.ree.es/archives/70/download_json?locale=es&date=2021-12-21' -> Headers: <CIMultiDictProxy('Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store', 'Connection': 'close', 'Content-Length': '860', 'X-Iinfo': '13-21160080-0 0CNN RT(1640078755131 83) q(0 -1 -1 4) r(0 -1) B15(11,1720275,0)', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'incap_ses_1105_1885724=egKjIQxCfB08qRNPxMZVDggg6OdwWEAAAAAKcuWeB9M2vIlszyygt8VSQ==; path=/; Domain=.esios.ree.es; Secure; SameSite=None')>
Forbidden error with 'https://api.esios.ree.es/archives/70/download_json?locale=es&date=2021-12-21' -> Headers: <CIMultiDictProxy('Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store', 'Connection': 'close', 'Content-Length': '751', 'X-Iinfo': '4-62349941-0 0CNN RT(1640079059342 21) q(0 -1 -1 -1) r(0 -1) B15(11,1720275,0)', 'Strict-Transport-Security': 'max-age=31536000')>
```_

**Comment by azogue** [comment]
This issue is about the _experimental_ `esios` custom component with API token, which has 0 support, sorry 😅

✨ The new version [v4](https://github.com/azogue/aiopvpc/releases/tag/v4.0.0) deprecates the `esios` component. For **beta-testing** it, please follow instructions in https://github.com/azogue/aiopvpc/pull/47#issuecomment-1376937590

Closing this one 👍
