### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [azogue/aiopvpc#48]
It would be very helpful if you could tag releases again. This would enable distributions to fetch the package from GitHub instead of PyPI.

Thanks

**Comment by azogue** [comment]
I missed it for v3.1.0 🙈, but that version won't link with Home Assistant. The dependency bump is [in the works](https://github.com/home-assistant/core/pull/85612) for [v4.0.0](https://github.com/azogue/aiopvpc/releases/tag/v4.0.0)

I need to take some time to make some CI Action for it when publishing, I'm super lost with GitHub Actions 😅, now only accustomed to use the GitLab CI 😰 

Thanks for the ping!
Closing this one
