### ISSUE TITLE
aiopvpc - Repository structure for v4.1.0 is not compliant

### ISSUE THREAD

**Issue by Whastie** [azogue/aiopvpc#52]
Hi

<Integration azogue/aiopvpc> Repository structure for v4.1.0 is not complian

Hacs gives me this error when I try to install this app.

Can you help me to install it?

thank you

**Comment by azogue** [comment]
> Repository structure for v4.1.0 is not complian

Hi @Whastie, sorry but I don't understand, **this is not an HACS integration**

This is just an external library to support a HA core integration `pvpc_hourly_pricing`...

**Comment by Whastie** [comment]
Can you tell me how to install it?

thanks

**Comment by azogue** [comment]
> Can you tell me how to install it?
> 
> thanks

It's meant to be **used with the HA core integration**, not as an isolated HA integration, sorry
