### ISSUE TITLE
openevse don't works in HA Hacs

### ISSUE THREAD

**Issue by Whastie** [azogue/aiopvpc#53]
It seems that the integration of openenve in home assistant, which is integrated using hacs, has stopped working.
Does anyone know the reason??

I do not have a username or password configured, although I also tried with a username and password.
Communication by mqtt through nodered does work.
The version I have installed is:
OpenEVSE 8.2.0.EU
Wi-Fi OpenEVSE 4.1.7
home assistant and hacs at the last level:
Home Assistant 2023.3.4
hack 1.31.0

Can somebody help me?
![image](https://user-images.githubusercontent.com/89639919/225159681-a1dbb711-572e-4de4-9bd5-0e728f90d943.png)

thank you

**Comment by azogue** [comment]
sorry, but I don't know that integration, nor the link with this library 🤷‍♂️

Closing this as unrelated
