### ISSUE TITLE
Integrar precio excedentes de autoconsumo en el índice

### ISSUE THREAD

**Issue by variasdesign** [azogue/aiopvpc#62]
Buenas.

Antes que nada agradecer el trabajo realizado en este proyecto, la integración de HASS es simplemente magnífica y nos ha ayudado a mantener un consumo más responsable y eficiente en nuestro hogar.

Tenemos placas solares que generan excedentes a menudo. Al principio creía que mi compañía eléctrica me compensaba los excedentes a una tarifa fija, pero al parecer es variable, como la del consumo general.

Me gustaría saber si es posible incorporar el índice de autoconsumo en la integración del PVPC. A continuación dejo el enlace del índice de autoconsumo:

[Índice de precios de autoconsumo](https://www.esios.ree.es/es/analisis/1739)

Muchas gracias.

**Comment by azogue** [comment]
Hola @variasdesign,

Para acceder vía API a los datos del precio de excedentes hace falta adquirir un **API Token** de ESIOS (https://api.esios.ree.es, se pide por email), y esta librería YA implementa ese acceso ✅

El problema es que está costando mucho **llevar los cambios a HA-Core** 😓; hay un par de PR (como [éste](https://github.com/home-assistant/core/pull/85767)) rondando desde enero de este año 🙈, con poco éxito (buena parte de la culpa es mía, por no haber podido dedicarles atención en su momento)

Pero, para _beta-testing_, si usas HACS, puedes añadir este _custom-component_: https://github.com/azogue/ha-pvpc-custom, que ya **integra todos los cambios** y, si le introduces un API token en el setup/opciones, te muestra más  sensores de precio, incluyendo ese precio horario de excedentes de autoconsumo ✅

<img width="671" alt="Screenshot 2023-08-19 a las 11 36 42" src="https://github.com/azogue/aiopvpc/assets/9748301/b6c6f156-9dae-48ab-aee6-9737905ce131">

**Comment by variasdesign** [comment]
Hola @azogue,

Muchas gracias por responder. Recuerdo que pedí un token a consultasios@ree.es allá por febrero de este año, pero lamentablemente nunca me contestaron. Acabo de mandar otra solicitud, a ver si ahora consigo algo.

Una vez lo tenga, me instalo la versión HACS de la integración; cuenta conmigo para el beta-testing 👌

**Comment by variasdesign** [comment]
Hola, de nuevo, @azogue,

Ya me han dado una clave de API para acceder a esios. La he introducido en la integración de Home Assistant pero me dos de los sensores me salen desactivados/no disponibles:
![image](https://github.com/azogue/aiopvpc/assets/135355267/25347ef0-fb29-4a07-99f5-04f8ff19d3c9)

No sé si tiene algo que ver con la API o con la integración. Gracias y un saludo :+1:

**Comment by azogue** [comment]
> pero dos de los sensores me salen desactivados/no disponibles:

Es así _by design_, ya que esos 2 sensores son más _rarunos_ y entiendo que la mayoría de usuarios no los necesitarán.

En la integración, se puede activar / desactivar cualquier sensor. Simplemente, esos 2 vienen **deshabilitados por defecto**

**Comment by azogue** [comment]
> Comprendo, gracias por tu célere respuesta. Entiendo que, por descarte, _Injection price_ es el sensor que se refiere al precio de compra de los excedentes de autoconsumo. ¿Es así? Gracias y un saludo.

Sí, exacto 👌. 

Corresponde al indicador '1739' de ESIOS. Las definiciones de los sensores están en https://github.com/azogue/aiopvpc/blob/e95300609ae15d70fae9fe902003b7accf5a62b1/aiopvpc/const.py#L50-L74
